### PR TITLE
fix marking of spec results

### PR DESCRIPTION
**Pull request by evan-scott-zocdoc**
Closes https://github.com/webdriverio/wdio-jasmine-framework/issues/97

### CODE REVIEW

**Comment by evan-scott-zocdoc** [comment]
@christian-bromann any idea what's going on with the tests? looks like the last bunch to master have similar problems

**Comment by markbrouch** [comment]
Probably not the issue, but `String.prototype.startsWith()` doesn't have full browser support (again, not sure why that would mess with the unit tests). Maybe try it with:
```js
params.payload.id.match(/^spec/)
```

**Comment by evan-scott-zocdoc** [comment]
@markbrouch I think it was the mocha upgrade back a bit ago. I'll try reverting it in this PR and see.

**Comment by markbrouch** [comment]
👍 well this fixed an issue I was having with saucelabs, so thanks!

**Comment by evan-scott-zocdoc** [comment]
Nvm, that wasn't it. Idk @christian-bromann but this change does fix things if you want to merge and push it out anyway.

**Comment by christian-bromann** [comment]
@evan-scott-zocdoc can you provide a minimal reproducible example for this?

**Comment by evan-scott-zocdoc** [comment]
@christian-bromann I spent about an hour looking at your test suite and honestly have no idea where to start

**Comment by christian-bromann** [comment]
@evan-scott-zocdoc no I want a project that can reproduce this issue in real life

**Comment by millerick** [comment]
@christian-bromann , here is a repo that shows that `test.passed` is no longer available:
https://github.com/millerick/wdio-no-passed-repro

Manually applying the change in this PR to that repo fixed the issue:
```
===
{"type":"afterTest","title":"google","fullName":"opens google","file":"/src/wdio-no-passed-repro/dist/test/fakeTests.js","parent":"Jasmine__TopLevel__Suite","passed":true,"duration":3007}
===
```

**Comment by millerick** [comment]
Thanks @christian-bromann , when can we expect a new version of the `wdio-jasmine-framework` package to be released?

**Comment by christian-bromann** [comment]
I am not sure..it looks like the tests is failing but they have been that way for a while. It must have to do with Jasmine being updated.

**Comment by millerick** [comment]
How can we see these tests?  I assume we would be able to make PRs that help move us towards a new release?

**Comment by christian-bromann** [comment]
> How can we see these tests?

see https://travis-ci.org/webdriverio/wdio-jasmine-framework/builds/365992827?utm_source=github_status&utm_medium=notification

> I assume we would be able to make PRs that help move us towards a new release?

Absolutely! It looks like upgrading Jasmine broke some things regarding retry of flaky tests. Once we can fix this I would be happy to release the changes.

**Pull request merged**
